name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install workspaces
        run: npm i

      - name: Typecheck
        run: npm run typecheck

      - name: Build core
        run: npm --workspace packages/core run build

      - name: Goldens (core)
        run: npm --workspace packages/core run golden

      - name: Idempotence (core)
        run: npm --workspace packages/core run idempotence

      - name: Profiles sanity (core)
        run: npm --workspace packages/core run profiles

      - name: Build extension
        run: npm -w texpatch-extension run build

      - name: Dist reproducibility
        run: bash scripts/check-dist-clean.sh

      - name: Size budgets
        run: bash scripts/size-check.sh
