name: Publish

on:
  release:
    types: [published]

jobs:
  publish-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install workspaces
        run: npm i

      - name: Build core
        run: npm -w texpatch-core run build

      - name: Publish texpatch-core to npm
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

  build-extension-artifact:
    runs-on: ubuntu-latest
    needs: publish-core
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install workspaces
        run: npm i

      - name: Build extension
        run: npm -w texpatch-extension run build

      - name: Package extension artifact
        env:
          EXT_VERSION: ${{ github.event.release.tag_name }}
        run: bash scripts/pack-extension.sh

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: texpatch-extension
          path: texpatch-extension.zip
