name: Release Drafter
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
